language: java

sudo: required

# required for oraclejdk9
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - oracle-java8-installer

matrix:
  allow_failures:
    - jdk: oraclejdk9
    - os: osx

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
 - chmod +x gradlew

# Display Gradle version instead of letting Travis execute './gradlew assemble' by default
install: ./gradlew -version

script:
  - java -version
  - ./gradlew -version
  - ./gradlew --refresh-dependencies clean check -Dscan